# Generated by Django 4.2.1 on 2025-06-04 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=100, verbose_name='Nombre del proyecto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del proyecto')),
                ('cantidad_trabajadores', models.IntegerField(default=0, verbose_name='Nº de trabajadores')),
                ('peso_residuo', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso estimado del residuo (kg)')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_revision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de revisión')),
                ('es_peligroso', models.BooleanField(default=False, verbose_name='¿Es un residuo peligroso?')),
                ('tipo_residuo', models.CharField(choices=[('organico', 'Orgánico'), ('inerte', 'Inerte'), ('peligroso', 'Peligroso')], max_length=50, verbose_name='Tipo de residuo')),
                ('documento', models.FileField(blank=True, upload_to='documentos/', verbose_name='Documento adjunto')),
                ('completo', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
