services:
  - type: web
    name: formulario-contratistas
    env: python
    buildCommand: ""
    startCommand: gunicorn contratistas_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: contratistas_project.settings
      - key: PYTHON_VERSION
        value: "3.11"
